### ISSUE TITLE
please label libdrs_f build#5 in conda-forge to be 'broken'

### ISSUE THREAD

**Issue by muryanto1** [conda-forge/libdrs_f-feedstock#16]
Hi @conda-forge/core,

Please move libdrs_f build#5 from main to broken on the conda-forge channel on anaconda.org
because we have a list of packages dependent on libdrs_f, and we would like to test the changes that picks up new libnetcdf 4.7.1 locally first, and upload to our own cdat/label/nightly channel, validate all dependent packages. Only after we finish our validation, we will then want to rebuild libdrs_f-feedstock and upload our packages to conda-forge

**Comment by muryanto1** [comment]
libdrs_f 3.1.2 build#5 was built to pick up libnetcdf 4.7.1, but I should have bumped the version number to 3.1.3 instead of increasing build number.
I would like request libdrs_f 3.1.2 build#5 to be relabeled to something not 'main'.
I will increase the version when I rebuild it for libnetcdf 4.7.1 , that way, in downstream package, I can pin libdrs_f to 3.1.2 when my downstream package can only work with libnetcdf 4.6.2.

**Comment by ocefpaf** [comment]
Just got here but it is closed. Do you still want it removed?

**Comment by muryanto1** [comment]
please ignore the request to remove the package(s). Thank you.
